name: LP Manager Indexer

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          cat << EOF > .env
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          RPC_URL=${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }}
          CHAIN_ID=${{ secrets.CHAIN_ID }}
          EOF

      - name: Run indexer
        run: npm start

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: indexer-logs
          path: |
            *.log
            logs/
          retention-days: 7
