name: LP Manager Indexer

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
        run: |
          echo "🔍 Checking environment variables:"
          echo "SUPABASE_URL: ${SUPABASE_URL:0:20}..."
          echo "SUPABASE_KEY: ${SUPABASE_KEY:0:20}..."
          echo "RPC_URL: ${RPC_URL:0:20}..."
          echo "CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}"
          echo "CHAIN_ID: ${CHAIN_ID}"
          echo ""
          echo "Checking if variables are empty:"
          [ -z "$SUPABASE_URL" ] && echo "❌ SUPABASE_URL is empty" || echo "✅ SUPABASE_URL has value"
          [ -z "$SUPABASE_KEY" ] && echo "❌ SUPABASE_KEY is empty" || echo "✅ SUPABASE_KEY has value"
          [ -z "$RPC_URL" ] && echo "❌ RPC_URL is empty" || echo "✅ RPC_URL has value"
          [ -z "$CONTRACT_ADDRESS" ] && echo "❌ CONTRACT_ADDRESS is empty" || echo "✅ CONTRACT_ADDRESS has value"
          [ -z "$CHAIN_ID" ] && echo "❌ CHAIN_ID is empty" || echo "✅ CHAIN_ID has value"

      - name: Run indexer
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
        run: npm start

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: indexer-logs
          path: |
            *.log
            logs/
          retention-days: 7
